version: "3.9"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: my_company_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-net

  spring-app:
    image: aminebarrani/stageproj:1.0
    container_name: spring-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/my_company_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"
    networks:
      - springboot-net

networks:
  springboot-net:

volumes:
  mysql_data:
